import { SolvedSpot } from './types';

// ============================================================
// Postflop spots for the trainer.
//
// The single spot below is an ILLUSTRATIVE SAMPLE so the postflop
// mode is playable out of the box. Real, exact solutions are
// generated by TexasSolver via `solver/solve.mjs`, which writes
// files into `src/trainer/spots/` that get merged in at build time.
//
// Do not treat the sample frequencies as exact GTO — they are
// hand-tuned to be directionally reasonable for demoing the UI.
// Replace them by running the solver (see solver/README.md).
// ============================================================

export const SAMPLE_SPOTS: SolvedSpot[] = [
  {
    id: 'sample_btn_vs_bb_QJ2',
    title: 'BTN c-bet decision — single-raised pot vs BB',
    street: 'flop',
    board: ['Qs', 'Jh', '2h'],
    pot: 5.5,
    effectiveStack: 97.5,
    toAct: 'ip',
    actions: ['check', 'bet_33', 'bet_75'],
    actionLabels: { check: 'Check', bet_33: 'Bet 33%', bet_75: 'Bet 75%' },
    source: 'sample',
    note: 'Illustrative sample. Generate the real solve with solver/solve.mjs.',
    hands: [
      { hand: 'AhKh', freqs: { check: 0.10, bet_33: 0.25, bet_75: 0.65 } }, // nut flush draw + gutter, bet big
      { hand: 'KhTh', freqs: { check: 0.15, bet_33: 0.30, bet_75: 0.55 } }, // OESD + flush draw
      { hand: 'AsAd', freqs: { check: 0.35, bet_33: 0.50, bet_75: 0.15 } }, // overpair, small bet / protect
      { hand: 'QdQc', freqs: { check: 0.05, bet_33: 0.35, bet_75: 0.60 } }, // top set, build pot
      { hand: 'JsJc', freqs: { check: 0.10, bet_33: 0.40, bet_75: 0.50 } }, // middle set
      { hand: 'KsQc', freqs: { check: 0.45, bet_33: 0.45, bet_75: 0.10 } }, // top pair good kicker
      { hand: 'AcQd', freqs: { check: 0.40, bet_33: 0.50, bet_75: 0.10 } }, // top pair top kicker, mix
      { hand: 'Th9h', freqs: { check: 0.20, bet_33: 0.25, bet_75: 0.55 } }, // OESD + flush draw, semi-bluff
      { hand: '8c7c', freqs: { check: 0.80, bet_33: 0.15, bet_75: 0.05 } }, // air, mostly give up
      { hand: '6d5d', freqs: { check: 0.85, bet_33: 0.10, bet_75: 0.05 } }, // air
      { hand: 'AhTd', freqs: { check: 0.55, bet_33: 0.30, bet_75: 0.15 } }, // gutshot + overcard
      { hand: 'KdKc', freqs: { check: 0.30, bet_33: 0.50, bet_75: 0.20 } }, // overpair
    ],
  },
];
