import { MODEL } from './model';
import {
  encodeSpot, Spot, FEATURE_DIM, ACTIONS, ActionClass,
  legalMaskFromFeatures,
} from './features';

// ============================================================
// Pure-TS forward pass for the distilled postflop policy.
//
// Loads weights from model.ts (base64 Float32, generated by ml/train.py),
// standardizes the SHARED encodeSpot() features with the saved train mean/std,
// runs a 2-hidden-layer ReLU MLP, softmaxes, then masks to LEGAL actions and
// renormalizes. Because encodeSpot is the same module used to prep training
// data, train and inference features are byte-for-byte aligned.
// ============================================================

function b64ToF32(b64: string): Float32Array {
  // atob exists in the browser/extension and in modern Node (>=16) globals, so
  // it works both in the bundled content script and in tsx test runs.
  const bin = atob(b64);
  const len = bin.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) bytes[i] = bin.charCodeAt(i);
  return new Float32Array(bytes.buffer);
}

interface LoadedModel {
  W1: Float32Array; b1: Float32Array;
  W2: Float32Array; b2: Float32Array;
  W3: Float32Array; b3: Float32Array;
  dims: Record<string, number[]>;
  mean: Float32Array;
  std: Float32Array;
}

let MODEL_CACHE: LoadedModel | null = null;

function getModel(): LoadedModel {
  if (MODEL_CACHE) return MODEL_CACHE;
  const w = MODEL.weights;
  MODEL_CACHE = {
    W1: b64ToF32(w.W1), b1: b64ToF32(w.b1),
    W2: b64ToF32(w.W2), b2: b64ToF32(w.b2),
    W3: b64ToF32(w.W3), b3: b64ToF32(w.b3),
    dims: MODEL.dims,
    mean: b64ToF32(MODEL.mean),
    std: b64ToF32(MODEL.std),
  };
  return MODEL_CACHE;
}

/** y = relu(x @ W + b), W stored row-major [in, out]. */
function denseRelu(x: Float32Array, W: Float32Array, b: Float32Array, din: number, dout: number): Float32Array {
  const out = new Float32Array(dout);
  for (let o = 0; o < dout; o++) {
    let acc = b[o];
    for (let i = 0; i < din; i++) acc += x[i] * W[i * dout + o];
    out[o] = acc > 0 ? acc : 0;
  }
  return out;
}

/** logits = x @ W + b (no activation). */
function dense(x: Float32Array, W: Float32Array, b: Float32Array, din: number, dout: number): Float32Array {
  const out = new Float32Array(dout);
  for (let o = 0; o < dout; o++) {
    let acc = b[o];
    for (let i = 0; i < din; i++) acc += x[i] * W[i * dout + o];
    out[o] = acc;
  }
  return out;
}

/**
 * Run the raw forward pass (standardize -> dense+ReLU -> dense+ReLU -> dense) on
 * an already-encoded RAW feature vector and return the UN-masked, pre-softmax
 * logits. Exposed for the train/serve parity test (tests/ml-parity.test.ts) so
 * the TS inference can be compared logit-for-logit against the numpy reference.
 * This is the exact same math predictPostflop() uses internally.
 */
export function forwardLogits(raw: Float32Array | number[]): number[] {
  const m = getModel();
  const x = new Float32Array(FEATURE_DIM);
  for (let i = 0; i < FEATURE_DIM; i++) x[i] = (raw[i] - m.mean[i]) / m.std[i];
  const h1Dim = m.dims.b1[0];
  const h2Dim = m.dims.b2[0];
  const outDim = m.dims.b3[0];
  const a1 = denseRelu(x, m.W1, m.b1, FEATURE_DIM, h1Dim);
  const a2 = denseRelu(a1, m.W2, m.b2, h1Dim, h2Dim);
  const logits = dense(a2, m.W3, m.b3, h2Dim, outDim);
  return Array.from(logits);
}

export interface PostflopPrediction {
  probs: Record<ActionClass, number>;
  /** argmax legal action class. */
  action: ActionClass;
}

/**
 * Predict the postflop action distribution for a spot. Probabilities are
 * masked to LEGAL actions (from the same features used at training) and
 * renormalized so they sum to 1.
 */
export function predictPostflop(spot: Spot): PostflopPrediction {
  const m = getModel();
  const raw = encodeSpot(spot); // shared encoder — identical to training

  // standardize
  const x = new Float32Array(FEATURE_DIM);
  for (let i = 0; i < FEATURE_DIM; i++) x[i] = (raw[i] - m.mean[i]) / m.std[i];

  const h1Dim = m.dims.b1[0];
  const h2Dim = m.dims.b2[0];
  const outDim = m.dims.b3[0];

  const a1 = denseRelu(x, m.W1, m.b1, FEATURE_DIM, h1Dim);
  const a2 = denseRelu(a1, m.W2, m.b2, h1Dim, h2Dim);
  const logits = dense(a2, m.W3, m.b3, h2Dim, outDim);

  // mask to legal actions from the RAW features (the mask lives in the vector)
  const mask = legalMaskFromFeatures(raw);
  for (let i = 0; i < outDim; i++) if (mask[i] < 0.5) logits[i] = -Infinity;

  // softmax over the masked logits
  let max = -Infinity;
  for (const v of logits) if (v > max) max = v;
  let sum = 0;
  const exp = new Float32Array(outDim);
  for (let i = 0; i < outDim; i++) {
    const e = logits[i] === -Infinity ? 0 : Math.exp(logits[i] - max);
    exp[i] = e;
    sum += e;
  }

  const probs = {} as Record<ActionClass, number>;
  let bestI = 0;
  let bestP = -1;
  for (let i = 0; i < ACTIONS.length; i++) {
    const p = sum > 0 ? exp[i] / sum : (mask[i] > 0.5 ? 1 : 0);
    probs[ACTIONS[i]] = p;
    if (p > bestP) { bestP = p; bestI = i; }
  }

  return { probs, action: ACTIONS[bestI] };
}

export const MODEL_ACCURACY = MODEL.accuracy;
